#!/bin/bash

check_rescue()
{
    for x in $(cat /proc/cmdline); do
    case $x in
        rescue)
            MODE=shell
            ;;
        console=*)
            TTY=${x#console=}
            if [ -e /dev/${TTY} ]; then
                echo ${TTY} >> /etc/securetty
            fi
            ;;
        esac
    done
}

setup_users()
{
    if [ ! -e /root ]; then
        mkdir -p /root
        chmod 0700 /root
    fi
    if [ ! -e /home/rancher ]; then
        mkdir -p /home/rancher
        chown rancher /home/rancher
    fi
}

setup_hosts()
{
    if [ -e /etc/hosts ]; then
        return 0
    fi

    HOSTNAME=$(</etc/hostname)
    cat > /etc/hosts << EOF
127.0.0.1	localhost localhost.localdomain
127.0.1.1	${HOSTNAME} ${HOSTNAME}.localdomain

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
}

setup_hostname()
{
    if [ -e /etc/hostname ]; then
        return 0
    fi

    if [ -e /var/lib/rancher/k3os/hostname ]; then
        cp /var/lib/rancher/k3os/hostname /etc/hostname
        return 0
    fi

    local mac="$(</sys/class/net/eth0/address)"
    if [ -z "$mac" ]; then
        mac=${RANDOM}
        return 0
    fi

    mkdir -p /var/lib/rancher/k3os
    HOSTNAME=k3os-${mac}
    echo $HOSTNAME > /var/lib/rancher/k3os/hostname
    cp /var/lib/rancher/k3os/hostname /etc/hostname
}

setup_manifests()
{
    mkdir -p /var/lib/rancher/k3s/server/manifests
    rsync -a --exclude='*.example' /usr/share/rancher/k3s/server/manifests/ /var/lib/rancher/k3s/server/manifests/
}

do_grow_live()
{
    parted $1 resizepart $2 yes 100%
    partprobe $1
    resize2fs $3
}

grow_live()
{
    if [ "$K3OS_MODE" != "local" ]; then
        return 0
    fi

    if [ -e /k3os/system/growpart ]; then
        read DEV NUM < /k3os/system/growpart
        if [ ! -e "${DEV}${NUM}" ]; then
            # /dev/sda2 => /dev/sda2
            # /dev/nvme0n1p2 => /dev/nvme0n1p2
            PART=$(blkid -L K3OS_STATE)

            # /dev/sda2 => /dev/sda
            # /dev/nvme0n1p2 => /dev/nvme0n1
            DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

            # /dev/sda2 => 2
            # /dev/nvme0n1p2 => 2
            NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
        fi
        pinfo Growing ${PART:=${DEV}${NUM}}
        do_grow_live $DEV $NUM $PART || true
        rm -f /k3os/system/growpart
    fi
}

setup_ssh()
{
    if [ ! -e /var/lib/rancher/k3os/ssh ]; then
        mkdir -p /var/lib/rancher/k3os
        cp -rf /etc/ssh /var/lib/rancher/k3os/ssh
    fi
    rm -rf /etc/ssh
    ln -s /var/lib/rancher/k3os/ssh /etc/ssh
}

setup_rancher_node()
{
    mkdir -p /etc/rancher
    mkdir -p /var/lib/rancher/k3os/node
    ln -s /var/lib/rancher/k3os/node /etc/rancher/
}

setup_ssh
setup_rancher_node
grow_live
setup_hostname
setup_hosts
setup_users
check_rescue
setup_manifests
