#!/bin/bash
set -e

. /usr/libexec/k3os/functions
. /usr/lib/os-release

config_initrd()
{
    k3os config --initrd
}

mount_sys()
{
    mount -o remount,rw /
	do_mkdir $1/run 0755
	do_mkdir $1/sys 0755
	do_mkdir $1/proc 0755
	do_mkdir $1/dev 0755
	mount -o "nodev,nosuid,noexec,relatime" -t proc proc /proc
    mount -o "noexec,nosuid,nodev" -t sysfs sysfs /sys
    mount -o "nosuid,noexec,relatime,size=10m,nr_inodes=248418,mode=755" -t devtmpfs dev /dev
	mount -o "nodev,nosuid,noexec,relatime,size=10%,mode=755" -t tmpfs tmpfs /run
}

setup_etc()
{
    mkdir -p /etc
    mount -t tmpfs none /etc
    cp -rfp /usr/etc/* /etc
}

setup_dev()
{
    lib/systemd/systemd-udevd --daemon --resolve-names=never
    udevadm trigger --type=subsystems --action=add
    udevadm trigger --type=devices --action=add
    udevadm settle || true
    udevadm control --exit
}

mount_sys
reinit_debug
setup_etc
setup_root
setup_dev
config_initrd

pinfo Bootstrapped ${PRETTY_NAME}
