#!/bin/bash

setup_motd()
{
    echo >> /etc/motd
    echo 'You can configure this system or install to disk using "sudo k3os install"' >> /etc/motd
}

setup_passwd()
{
    # no passwords in live mode
    passwd -d rancher >/dev/null 2>&1
    sed -i '/pam_unix/s/$/ nullok_secure/g' /etc/pam.d/common-auth
}

mount_iso()
{
    mkdir -p /mnt/iso
    if mount -L K3OS /mnt/iso; then
        if [ -d /mnt/iso/oem ]; then
            mount --bind /mnt/iso/oem /usr/share/k3os/oem
        else
            umount /mnt/iso
        fi
    fi
}

setup_passwd
setup_motd
mount_iso
