#!/bin/bash
set -e

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

. /usr/libexec/k3os/functions
. /usr/lib/os-release

pinfo Bootstrapping $PRETTY_NAME

if [ "$K3OS_DEBUG" = "true" ]; then
    set -x
fi

if ! ${SCRIPTS}/bootstrap; then
    rescue
fi

reinit_debug

source ${SCRIPTS}/mode

trap rescue EXIT

pinfo Running mode: ${K3OS_MODE}
source $SCRIPTS/mode-${K3OS_MODE}

pinfo Booting system
source $SCRIPTS/boot

exec chroot . $SCRIPTS/run-init
